# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Taps
tap homebrew/dupes
tap phinze/cask
tap caskroom/versions
tap jimbojsb/launchrocket

# Install formulae
install ack
install brew-cask
install fish
install git
install go
install hub
install node
install tree
install vim

# Remove outdated versions from the cellar
cleanup
