# Antigen (https://github.com/zsh-users/antigen)
source $HOME/.zsh/antigen/antigen.zsh

# Aliases, functions, and exports
for file in ~/.{aliases,functions,exports}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Pure prompt (https://github.com/sindresorhus/pure)
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen apply

# DNVM (https://github.com/aspnet/dnvm)
source dnvm.sh

# Rbenv (https://github.com/sstephenson/rbenv)
eval "$(rbenv init -)"

# Gulp (https://github.com/gulpjs/gulp)
eval "$(gulp --completion=zsh)"

# The Fuck (https://github.com/nvbn/thefuck)
eval "$(thefuck --alias)"
