# Aliases, functions, and exports
for file in ~/.{aliases,functions,exports}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Antibody (https://github.com/caarlos0/antibody)
source "$HOME/.zsh/plugins.sh"

# DNVM (https://github.com/aspnet/dnvm)
source dnvm.sh

# Rbenv (https://github.com/sstephenson/rbenv)
eval "$(rbenv init -)"
